### ISSUE TITLE
贡献第一步：如何从头开始启动pont项目？

### ISSUE THREAD

**Issue by xwxgjs** [pont2/pont#1]
## 配置开发环境

> Windows 系统需要配置 WSL。目前项目只能在类 Linux 系统运行。推荐使用最新的 WSL2

> 使用 WSL2 时，请注意不要跨文件系统操作。具体问题请参照 [跨文件系统的文件存储和性能](https://docs.microsoft.com/zh-cn/windows/wsl/filesystems#file-storage-and-performance-across-file-systems)

### 1. 安装 Node.js

我们推荐使用 nvm 安装和管理 Node.js。nvm 允许同时在机器上安装、运行多个 Node.js 版本。

执行 `git clone https://github.com/nvm-sh/nvm.git`，将项目下载到本地，然后执行 sudo ./install.sh 安装 nvm。

> 如果你喜欢用 ssh，执行 `git clone git@github.com:nvm-sh/nvm.git`
> 
> 如果使用 https 协议无法下载，可以使用镜像站下载，比如 fastgit。执行 `git clone https://hub.fastgit.org/nvm-sh/nvm.git`

代码清单：
```sh
git clone https://github.com/nvm-sh/nvm.git
cd nvm
sudo ./install.sh
``` 

初始化需要一段时间，当显示如下内容时，可以关闭当前终端窗口，开启新窗口之后即可正常使用 nvm。

![nvm 安装完成](https://user-images.githubusercontent.com/77133362/166131031-67c4d7fc-5aa8-4672-b202-80fcf9b60a5c.png)

nvm 安装完成之后，下面可以使用 nvm 安装 Node.js。可运行以下命令配置 Node.js 下载镜像地址，以大幅缩短下载时间。
```sh
export NVM_NODEJS_ORG_MIRROR=https://npmmirror.com/mirrors/node/
```

然后运行 `nvm install` 命令安装 Node.js，推荐安装 LTS 版本，相对来说更稳定。比如说：
```sh
nvm install 16.15.0
```

稍等一段时间，提示如下内容表示安装完成

![Node.js 安装完成](https://user-images.githubusercontent.com/77133362/166131190-268a3403-a357-422f-bf44-c65e16126657.png)

此时我们的运行环境准备工作已经完成，下面执行项目初始化

### 2. 初始化项目

执行 `git clone https://github.com/pont2/pont.git`，将项目下载到本地。

> 如果你喜欢用 ssh，执行 `git@github.com:pont2/pont.git`
> 
> 如果使用 https 协议无法下载，可以使用镜像站下载，比如 fastgit。执行 `git clone https://hub.fastgit.org/pont2/pont.git`

```sh
git clone https://github.com/pont2/pont.git
cd pont
```

pont 项目使用的是 yarn + lerna。需要启用 yarn 环境。
由于当前安装的 Node.js 版本 >=16，因此可以使用 corepack 启用 yarn 命令。需要在终端运行以下命令：
```sh
corepack enable
```

运行完成后安装全局的 lerna
```sh
npm i lerna -g
```

安装完成后运行
```sh
lerna bootstrap
```
> 当前版本仓库管理者错误提交了内网的 yarn.lock，请删除后再运行上述命令

初始化可能需要很长时间。

![初始化完成](https://user-images.githubusercontent.com/77133362/166131665-45146ae0-5ca0-4989-b6d9-e085984afd00.png)

执行以下命令：开启开发旅程
```sh
yarn watch
```
> 这一步不知道需要等多久……直到发稿，还没有成功启动。运行不报错，控制台无输出，就卡在这了。

**Comment by jasonHzq** [comment]
这样就已经启动完了
